const {test,expect}=require('@playwright/test');const fs=require('node:fs');
async function fits(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);const clipped=await page.locator('.mechanism svg text').evaluateAll(ts=>ts.filter(t=>{const a=t.getBoundingClientRect(),b=t.ownerSVGElement.getBoundingClientRect();return a.left<b.left-2||a.right>b.right+2||a.top<b.top-2||a.bottom>b.bottom+2}).map(t=>t.textContent));expect(clipped).toEqual([]);}
for(const slug of ['data-engineering','software-engineering','distinguished-engineer','genai-engineering','technology-breakthroughs','ci-cd-github-actions','apis-microservices'])test('Day19 mechanism '+slug,async({page},info)=>{await page.goto('/Day19/'+slug+'.html');if(slug==='data-engineering')await page.locator('#coreExtension > summary').click();const w=page.locator('#world');await expect(w).not.toBeEmpty();
 if(slug==='data-engineering'){await expect(w).toContainText('6/6');await page.locator('#layoutMode').selectOption('clustered');await expect(w).toContainText('1/6');await page.locator('#predicateMode').selectOption('wrapped');await expect(w).toContainText('6/6');}
 if(slug==='software-engineering'){await page.locator('#abaNext').click();await page.locator('#abaNext').click();await expect(w).toContainText('WOULD PASS');await page.locator('#abaCheck').selectOption('stamp');await expect(w).toContainText('REJECTED');}
 if(slug==='distinguished-engineer'){await expect(w).toContainText('two-way door');await page.locator('#rollbackTested').selectOption('no');await expect(w).toContainText('not-yet-reversible');}
 if(slug==='genai-engineering'){await expect(w).toContainText('INFRA ERROR');await page.locator('#memoryCeiling').selectOption('2');await expect(w).toContainText('PASS');}
 if(slug==='technology-breakthroughs'){await expect(w).toContainText('key released: true');await page.locator('#attestationMatch').selectOption('mismatch');await expect(w).toContainText('key released: false');}
 if(slug==='ci-cd-github-actions'){await expect(w).toContainText('PASS');await page.locator('#artifactDigest').selectOption('bbb');await expect(w).toContainText('BLOCK');}
 if(slug==='apis-microservices'){await expect(w).toContainText('ACCEPT amount 50');await page.locator('#bodyVersion').selectOption('tampered');await expect(w).toContainText('REJECT before effect');}
 await fits(page);await w.screenshot({path:info.outputPath(slug+'.png')});});
test('Day19 product pruning, highlights and private export',async({page})=>{await page.goto('/Day19/data-engineering.html');for(const p of ['db','sf']){await page.locator('#'+p+'Layout').selectOption('clustered');for(let i=0;i<3;i++)await page.locator('#'+p+'Next').click();await expect(page.locator('#'+p+'State')).toContainText('scan 1 chunk');await expect(page.locator('#'+p+'Line2')).toHaveClass('active');await page.locator('#'+p+'Reset').click();await expect(page.locator('#'+p+'State')).toContainText('Step 0/3');}await page.locator('#productGrade').click();await expect(page.locator('#productScore')).toContainText('Answer both');await page.locator('#productQ0').selectOption('0');await page.locator('#productQ1').selectOption('0');await page.locator('#productGrade').click();await expect(page.locator('#productScore')).toContainText('1/2');await page.locator('#productQ1').selectOption('1');await page.locator('#productGrade').click();await expect(page.locator('#productScore')).toContainText('2/2');await page.locator('#save').click();await page.reload();await expect(page.locator('#productQ1')).toHaveValue('1');const pending=page.waitForEvent('download');await page.locator('#export').click();const d=await pending;const j=JSON.parse(fs.readFileSync(await d.path(),'utf8'));await d.delete();expect(j.product_assessment.answers).toEqual(['0','1']);expect(j.product_assessment.attempts.map(x=>x.score)).toEqual([1,2]);await fits(page);});
